### PR TITLE
Catch task errors

### LINKED ISSUE #107: Correctly handle exceptions
If an exception occurs make sure we are at least in a valid state.

- [x] An exception in pipeline.add should leave the pipeline unchanged.
- [ ] An exception while constructing a scheduler is perfectly fine.
- [ ] An exception in scheduler.run should stop processing and tidy up the queue/intermediate values.

### PR DESCRIPTION
**Pull request by lawben**
This PR adds the ability to catch errors in tasks that run either on the main thread or in other threads.
I am not entirely sure what needs to be cleared in case of an error. Currently, I am just throwing an error on the main thread. 

Things that were actually added: 
  - `scheduler_test.cpp` (second half)
  - `abstract_task_container.h`: `failed()` and `get_error()`
  - `scheduler.h`: `assert_no_task_failed()` 

It should not be merged before #128. 
Closes #107.

### CODE REVIEW

File: source/yats/include/yats/scheduler.h [hunk 1]
```diff
@@ -31,60 +49,116 @@ class scheduler
...
+    }
+
+    void assert_no_task_failed()
+    {
+        // If a task failed, we want to catch this in the main thread and throw an error for the user.
+        if (m_task_error) {
+            try
+            {
+                std::rethrow_exception(m_task_error);
+            } catch (const std::exception& exception)
```
Comment (mflueggen) [inline source/yats/include/yats/scheduler.h]: How do we write try... catch blocks? New line here?

File: source/tests/yats-test/scheduler_test.cpp [hunk 2]
```diff
@@ -25,10 +29,27 @@ TEST(scheduler_test, multithreaded_timing_test)
...
 
     auto duration = std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();
+
     EXPECT_GE(duration, 100);
     EXPECT_LE(duration, 500);
 }
 
+TEST(scheduler_test, run_twice)
+{
+    yats::pipeline pipeline;
```
Comment (mflueggen) [inline source/tests/yats-test/scheduler_test.cpp]: Since we are using the yats namespace in tests, please remove the "yats::" identifier in tests.

File: source/tests/yats-test/scheduler_test.cpp [hunk 3]
```diff
@@ -61,3 +61,177 @@ TEST(scheduler_test, throw_on_creation)
     EXPECT_THROW(yats::scheduler scheduler(std::move(pipeline)), std::runtime_error);
 }
 
+TEST(scheduler_test, catch_task_exception)
+{
+    pipeline pipeline;
+
+    struct task {
+       void run()
+      {
```
Comment (mflueggen) [inline source/tests/yats-test/scheduler_test.cpp]: Formatting issue.

File: source/tests/yats-test/scheduler_test.cpp [hunk 4]
```diff
@@ -61,3 +61,177 @@ TEST(scheduler_test, throw_on_creation)
...
+    scheduler scheduler(std::move(pipeline));
+    EXPECT_THROW(scheduler.run(), std::runtime_error);
+}
+
+TEST(scheduler_test, catch_chained_task_exception)
+{
+    pipeline pipeline;
+
+    struct task {
+      slot<int, 0> run()
```
Comment (mflueggen) [inline source/tests/yats-test/scheduler_test.cpp]: Formatting issue.

File: source/tests/yats-test/scheduler_test.cpp [hunk 5]
```diff
@@ -61,3 +61,177 @@ TEST(scheduler_test, throw_on_creation)
...
+      {
+          throw std::runtime_error("failed foo");
+          return 1;
+      }
+    };
+
+    struct task2 {
+      void run(yats::slot<int, 0> input)
```
Comment (mflueggen) [inline source/tests/yats-test/scheduler_test.cpp]: Formatting issue.

File: source/tests/yats-test/scheduler_test.cpp [hunk 6]
```diff
@@ -61,3 +61,177 @@ TEST(scheduler_test, throw_on_creation)
...
+    scheduler scheduler(std::move(pipeline));
+    EXPECT_THROW(scheduler.run(), std::runtime_error);
+}
+
+TEST(scheduler_test, catch_last_task_exception)
+{
+    pipeline pipeline;
+
+    struct task {
+      slot<int, 0> run()
```
Comment (mflueggen) [inline source/tests/yats-test/scheduler_test.cpp]: Formatting issue.

File: source/tests/yats-test/scheduler_test.cpp [hunk 7]
```diff
@@ -61,3 +61,177 @@ TEST(scheduler_test, throw_on_creation)
...
+      {
+          return 1;
+      }
+    };
+
+    struct task2 {
+      void run(yats::slot<int, 0>)
```
Comment (mflueggen) [inline source/tests/yats-test/scheduler_test.cpp]: Formatting issue.

File: source/tests/yats-test/scheduler_test.cpp [hunk 8]
```diff
@@ -61,3 +61,177 @@ TEST(scheduler_test, throw_on_creation)
...
+    scheduler scheduler(std::move(pipeline));
+    EXPECT_THROW(scheduler.run(), std::runtime_error);
+}
+
+TEST(scheduler_test, catch_last_task_main_thread_exception)
+{
+    pipeline pipeline;
+
+    struct task {
+      slot<int, 0> run()
```
Comment (mflueggen) [inline source/tests/yats-test/scheduler_test.cpp]: Formatting issue.

File: source/tests/yats-test/scheduler_test.cpp [hunk 9]
```diff
@@ -61,3 +61,177 @@ TEST(scheduler_test, throw_on_creation)
...
+      {
+          return 1;
+      }
+    };
+
+    struct task2 {
+      thread_group thread_constraints()
```
Comment (mflueggen) [inline source/tests/yats-test/scheduler_test.cpp]: Formatting issue.

File: source/tests/yats-test/scheduler_test.cpp [hunk 10]
```diff
@@ -61,3 +61,177 @@ TEST(scheduler_test, throw_on_creation)
...
+    scheduler scheduler(std::move(pipeline));
+    EXPECT_THROW(scheduler.run(), std::runtime_error);
+}
+
+TEST(scheduler_test, catch_last_task_any_thread_exception)
+{
+    pipeline pipeline;
+
+    struct task {
+      slot<int, 0> run()
```
Comment (mflueggen) [inline source/tests/yats-test/scheduler_test.cpp]: Formatting issue.

File: source/tests/yats-test/scheduler_test.cpp [hunk 11]
```diff
@@ -61,3 +61,177 @@ TEST(scheduler_test, throw_on_creation)
...
+      {
+          return 1;
+      }
+    };
+
+    struct task2 {
+      thread_group thread_constraints()
```
Comment (mflueggen) [inline source/tests/yats-test/scheduler_test.cpp]: Formatting issue.

File: source/tests/yats-test/scheduler_test.cpp [hunk 12]
```diff
@@ -61,3 +61,177 @@ TEST(scheduler_test, throw_on_creation)
...
+    scheduler scheduler(std::move(pipeline));
+    EXPECT_THROW(scheduler.run(), std::runtime_error);
+}
+
+TEST(scheduler_test, catch_last_task_main_thread_after_any_thread_exception)
+{
+    pipeline pipeline;
+
+    struct task {
+      thread_group thread_constraints()
```
Comment (mflueggen) [inline source/tests/yats-test/scheduler_test.cpp]: Formatting issue.

File: source/tests/yats-test/scheduler_test.cpp [hunk 13]
```diff
@@ -61,3 +61,177 @@ TEST(scheduler_test, throw_on_creation)
...
+      slot<int, 0> run()
+      {
+          std::this_thread::sleep_for(std::chrono::milliseconds(100));
+          throw std::runtime_error("failed foo");
+          return 1;
+      }
+    };
+
+    struct task2 {
+      thread_group thread_constraints()
```
Comment (mflueggen) [inline source/tests/yats-test/scheduler_test.cpp]: Formatting issue.

File: source/yats/include/yats/scheduler.h [hunk 14]
```diff
@@ -46,10 +54,20 @@ class scheduler
         while (auto guard = m_condition.wait_main(thread_group::MAIN))
         {
             auto current_task = get(thread_group::MAIN);
-            m_tasks[current_task]->run();
+            auto& task = m_tasks[current_task];
+
+            task->run();
```
Comment (mflueggen) [inline source/yats/include/yats/scheduler.h]: Code duplication. See line 26.

File: source/yats/include/yats/task_container.h [hunk 15]
```diff
@@ -80,8 +91,15 @@ class task_container : public abstract_task_container
...
     {
-        m_options->make_updates_visible(&m_task);
-        invoke(std::make_index_sequence<helper::input_count>());
+        try
+        {
+            m_options->make_updates_visible(&m_task);
+            invoke(std::make_index_sequence<helper::input_count>());
+        } catch (const std::exception&)
+        {
+            m_error = std::current_exception();
```
Comment (mflueggen) [inline source/yats/include/yats/task_container.h]: This might not be thread safe.

Comment (lawben) [reply source/yats/include/yats/task_container.h]: a task does not need to be thread safe, does it? this is executed on exactly one thread

Comment (mflueggen) [reply source/yats/include/yats/task_container.h]: I think you are right. There seems to be an instance of std::current_execption for each individual thread.

File: source/tests/yats-test/scheduler_test.cpp [hunk 16]
```diff
@@ -61,3 +61,188 @@ TEST(scheduler_test, throw_on_creation)
     EXPECT_THROW(yats::scheduler scheduler(std::move(pipeline)), std::runtime_error);
 }
 
+TEST(scheduler_test, catch_task_exception)
+{
+    pipeline pipeline;
+
+    struct task
+    {
+    	  void run()
```
Comment (mflueggen) [inline source/tests/yats-test/scheduler_test.cpp]: there is a tab.

File: source/tests/yats-test/scheduler_test.cpp [hunk 17]
```diff
@@ -61,3 +61,188 @@ TEST(scheduler_test, throw_on_creation)
...
+        {
+        	  throw std::runtime_error("failed foo");
```
Comment (mflueggen) [inline source/tests/yats-test/scheduler_test.cpp]: there is a tab
