### PR TITLE
Fix formatting

### LINKED ISSUE #53: Use snake_case instead of CamelCase
Rename all names in all files to snake_case. This also includes file names but excludes template parameter names.

### PR DESCRIPTION
**Pull request by Zanthelo**
Closes #53

### CODE REVIEW

File: source/yats/include/yats/Identifier.h [hunk 1]
```diff
@@ -7,78 +7,81 @@ namespace yats
...
+name(const char* string, size_t length)
 {
-	uint64_t value = 0;
+    uint64_t value = 0;
 
-	// The length of a string is limited to 12 characters excluding the termination character.
-	constexpr int max_length = 12;
-	const int truncated_length = std::min(static_cast<int>(length), max_length);
+    // The length of a string is limited to 12 characters excluding the termination character.
+    constexpr int max_length       = 12;
```
Comment (lawben) [inline source/yats/include/yats/Identifier.h]: I'm not a fan of this. it should be `constexpr int max_length = 12;`

File: source/yats/include/yats/Identifier.h [hunk 2]
```diff
@@ -7,78 +7,81 @@ namespace yats
...
+    const int     truncated_length = std::min(static_cast<int>(length), max_length);
```
Comment (lawben) [inline source/yats/include/yats/Identifier.h]: same as above, no variable aligning

File: source/yats/include/yats/Identifier.h [hunk 3]
```diff
@@ -7,78 +7,81 @@ namespace yats
...
-	value = value | truncated_length;
+    // Lowest 4 bits encode the length of the string.
+    value = value | truncated_length;
 
-	return value;
+    return value;
 }
 
-}  // namespace yats
+}    // namespace yats
```
Comment (lawben) [inline source/yats/include/yats/Identifier.h]: 2 spaces should be enough here instead of 4

File: source/yats/include/yats/Input.h [hunk 4]
```diff
@@ -12,21 +12,30 @@ template<typename T, uint64_t Id>
 class Input
 {
 public:
-	using value_type = T;
-	constexpr static uint64_t ID = Id;
+    using value_type             = T;
```
Comment (lawben) [inline source/yats/include/yats/Input.h]: no variable aligning

File: source/yats/include/yats/InputConnector.h [hunk 5]
```diff
@@ -11,42 +11,45 @@ class AbstractTaskConfigurator;
...
 class InputConnector : public AbstractInputConnector
 {
 public:
-	InputConnector() = default;
+    InputConnector() = default;
 
-	InputConnector(const InputConnector<T>& other) = delete;
-	InputConnector(InputConnector<T>&& other) = delete;
+    InputConnector(const InputConnector<T>& other) = delete;
+    InputConnector(InputConnector<T>&& other)      = delete;
```
Comment (lawben) [inline source/yats/include/yats/InputConnector.h]: no variable aligning

File: source/yats/include/yats/OutputConnector.h [hunk 6]
```diff
@@ -11,28 +11,27 @@ namespace yats
...
+    {
+        input << *this;
+        return *this;
+    }
 };
 
-
 // Allows the connection of an input to the output.
-template <typename T>
+template<typename T>
```
Comment (lawben) [inline source/yats/include/yats/OutputConnector.h]: can we keep the space here?

File: source/yats/include/yats/TaskConfigurator.h [hunk 7]
```diff
@@ -13,138 +13,134 @@ namespace yats
...
-			tasks.emplace_back(configurators[i]->make(std::move(helpers[i])));
-		}
-
-		return tasks;
-	}
+    AbstractTaskConfigurator()          = default;
+    virtual ~AbstractTaskConfigurator() = default;
+
+    virtual std::unique_ptr<AbstractTaskContainer>    make(std::unique_ptr<AbstractConnectionHelper> helper) const = 0;
+    virtual std::unique_ptr<AbstractConnectionHelper> make2() const                                                = 0;
```
Comment (lawben) [inline source/yats/include/yats/TaskConfigurator.h]: yea, this is terrible 😂

File: source/yats/include/yats/Util.h [hunk 8]
```diff
@@ -13,196 +13,195 @@ namespace yats
...
-	{
-		return invalid_index;
-	}
-
-	static constexpr uint64_t value = find();
-	static_assert(value != invalid_index, "Could not find identifier in tuple.");
+    static constexpr size_t invalid_index = std::numeric_limits<size_t>::max();
+
+    template<size_t Index = 0, typename Tuple = T>
+        static constexpr std::enable_if_t < Index<std::tuple_size<Tuple>::value, size_t> find()
```
Comment (lawben) [inline source/yats/include/yats/Util.h]: the spacing here is really confusing

File: source/yats/include/yats/Identifier.h (hunk 3 above)
Comment (Highlife1911) [reply source/yats/include/yats/Identifier.h]: I would remove `// namespace yats` completely.

File: source/yats/include/yats/Identifier.h (hunk 1 above)
Comment (Highlife1911) [reply source/yats/include/yats/Identifier.h]: i agree, this looks terrible most of the time.

File: source/yats/include/yats/TaskConfigurator.h (hunk 7 above)
Comment (mflueggen) [inline source/yats/include/yats/TaskConfigurator.h]: What is make2()?

Comment (Highlife1911) [reply source/yats/include/yats/TaskConfigurator.h]: Solving these problems is not part of this pull request. This is only about changing the format to snake_case. Also there is currently no issue that is about documenting and renaming badly named functions. The reason for this is that most of the open issues are about removing code, changing the interface or the behavior of a function. Documenting the code before these changes are done is not viable because then our documentation is immediately outdated.
