### PR TITLE
Fix unnecessary copy in connection

### LINKED ISSUE #100: Invoke copy bug
Each connection copies a parameter twice.

### LINKED ISSUE #103: The TaskContainer should move values when possible.
A connection should move as much as possible.

### PR DESCRIPTION
**Pull request by Highlife1911**
Closes #100 
Closes #103

### CODE REVIEW

File: source/tests/yats-test/taskcontainer_test.cpp [hunk 1]
```diff
@@ -0,0 +1,23 @@
+#include <gmock/gmock.h>
+
+#include <yats/slot.h>
+#include <yats/task_container.h>
+#include <yats/scheduler.h>
+
+#include <memory>
+
+TEST(taskcontainer_test, return_parameters)
```
Comment (Zanthelo) [inline source/tests/yats-test/taskcontainer_test.cpp]: Should be task_container_test, to be consistent with task_container

File: source/tests/yats-test/taskcontainer_test.cpp [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+    auto lambda_source = pipeline.add([]() -> yats::slot<std::unique_ptr<int>, 1> { return std::make_unique<int>(30); });
+    auto lambda_target = pipeline.add([&test_int](yats::slot<std::unique_ptr<int>, 1> value) mutable { test_int = **value; });
+
+    lambda_source->output<1>() >> lambda_target->input<1>();
+
+    yats::scheduler scheduler(pipeline);
+    scheduler.run();
+
+    EXPECT_EQ(test_int, 30);
+}
```
Comment (Zanthelo) [inline source/tests/yats-test/taskcontainer_test.cpp]: Another test where one output writes into two inputs would be nice. Right now task_containers copy_value is never used.

File: source/yats/include/yats/task_container.h [hunk 3]
```diff
@@ -89,27 +88,50 @@ class task_container : public abstract_task_container
...
+    template <typename SlotType, typename ValueType = typename SlotType::value_type>
+    std::enable_if_t<std::is_copy_constructible<ValueType>::value, ValueType> copy_value(SlotType& value)
+    {
+        return value.clone();
+    }
+
+    template <typename SlotType, typename ValueType = typename SlotType::value_type>
+    std::enable_if_t<!std::is_copy_constructible<ValueType>::value, ValueType> copy_value(SlotType&)
+    {
+        throw std::runtime_error("An not copyable type cannot be used in multiple connections.");
```
Comment (Zanthelo) [inline source/yats/include/yats/task_container.h]: "A" instead of "An"

File: source/yats/include/yats/task_container.h [hunk 4]
```diff
@@ -89,27 +88,50 @@ class task_container : public abstract_task_container
...
-        auto value = queue.front();
+        auto& queue = std::get<index>(*m_input);
+        auto value = std::move(queue.front());
         queue.pop();
 
         return value;
     }
 
+    template <typename SlotType, typename ValueType = typename SlotType::value_type>
+    std::enable_if_t<std::is_copy_constructible<ValueType>::value, ValueType> copy_value(SlotType& value)
```
Comment (Zanthelo) [inline source/yats/include/yats/task_container.h]: value should be a const reference

File: source/yats/include/yats/task_container.h [hunk 5]
```diff
@@ -89,27 +88,50 @@ class task_container : public abstract_task_container
...
+    {
+        return value.clone();
+    }
+
+    template <typename SlotType, typename ValueType = typename SlotType::value_type>
+    std::enable_if_t<!std::is_copy_constructible<ValueType>::value, ValueType> copy_value(SlotType&)
```
Comment (Zanthelo) [inline source/yats/include/yats/task_container.h]: value should be a const reference

File: source/yats/include/yats/task_container.h [hunk 6]
```diff
@@ -89,27 +88,50 @@ class task_container : public abstract_task_container
...
+        throw std::runtime_error("An not copyable type cannot be used in multiple connections.");
+    }
+
     template <size_t index = 0, typename T = typename helper::output_type, typename Output = std::enable_if_t<std::is_same<T, void>::value, T>>
-    std::enable_if_t<(index < helper::output_count)> write(Output& output)
+    std::enable_if_t<(index < helper::output_count)> write(Output output)
     {
         auto& value = std::get<index>(output);
-        for (auto& callback : std::get<index>(m_output))
+        auto following_nodes = std::get<index>(m_output);
```
Comment (Zanthelo) [inline source/yats/include/yats/task_container.h]: should be a const reference

File: source/yats/include/yats/task_container.h [hunk 7]
```diff
@@ -89,27 +88,50 @@ class task_container : public abstract_task_container
...
+        for (size_t i = 1; i <= following_nodes.size(); ++i)
         {
-            callback(value);
+            auto& callback = following_nodes[i - 1];
```
Comment (Zanthelo) [inline source/yats/include/yats/task_container.h]: should be const aswell

File: source/yats/include/yats/task_container.h [hunk 8]
```diff
@@ -89,27 +88,50 @@ class task_container : public abstract_task_container
...
+    }
+
     template <size_t index = 0, typename T = typename helper::output_type, typename Output = std::enable_if_t<std::is_same<T, void>::value, T>>
-    std::enable_if_t<(index < helper::output_count)> write(Output& output)
+    std::enable_if_t<(index < helper::output_count)> write(Output output)
     {
         auto& value = std::get<index>(output);
-        for (auto& callback : std::get<index>(m_output))
+        auto following_nodes = std::get<index>(m_output);
+        for (size_t i = 1; i <= following_nodes.size(); ++i)
```
Comment (Zanthelo) [inline source/yats/include/yats/task_container.h]: I find it nicer to start at 0, since it's more consistent

File: source/yats/include/yats/threadpool.h [hunk 9]
```diff
@@ -0,0 +1,15 @@
+#pragma once
```
Comment (Zanthelo) [inline source/yats/include/yats/threadpool.h]: This file should not be part of this pull request

File: source/tests/yats-test/taskcontainer_test.cpp (hunk 1 above)
Comment (Highlife1911) [reply source/tests/yats-test/taskcontainer_test.cpp]: taskconfigurator does it this way too.

File: source/yats/include/yats/threadpool.h (hunk 9 above)
Comment (Highlife1911) [reply source/yats/include/yats/threadpool.h]: Something went wrong here. I searched for this file when doing the other issue.
